{{- if(.Values.createServiceAccount)}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.vaultRole }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
